### ISSUE TITLE
console dev mode warning when opening pool table V2

### ISSUE THREAD

**Issue by zavelevsky** [bancorprotocol/webapp-v3#196]
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
Check the render method of `Tooltip`.

The problem is we try to pass ref to a function component.

in Tooltip.tsx: cloneElement(children, { ref: buttonRef })
this can't be done because we pass Button as the children in PoolsTableCellActions.tsx and Button is a function component

**Comment by RanCohenn** [comment]
Stale
