### ISSUE TITLE
deposit wallet not connected

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp-v3#202]
when trying to deposit before connecting wallet, the popup CTA should follow this:
- [x] IF input field is empty -> CTA text: "Enter amount"
- [x] IF input field is NOT empty -> CTA text: "Connect your wallet"
- [x] at the end of the connect wallet flow, return to the deposit popup and make sure that IF input field had data in it, keep it and do not null it out.

**Comment by pingustar** [comment]
stale, will be fixed with new modal refactor
