### ISSUE TITLE
When failing to connect a wallet (just close metamask) the app doesn't recover

### ISSUE THREAD

**Issue by zavelevsky** [bancorprotocol/webapp-v3#217]
click connect a wallet and choose metamask
when metamask pops up just close it.
You will see and error indication.
Try to connect again.
You always see this instead of the wallet select:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/672016/167248358-2d0cbb01-facb-49d8-8356-5ccaf2de8dae.png">

**Comment by pingustar** [comment]
closing because of duplicate #374
