### ISSUE TITLE
standard rewards APR fix

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp-v3#285]
#182 

current:

Calculating StandardRewards APR:
sum of all programs where pool is the same (rewardsAmount24h.usd * 365 / programStake.usd * 100)

updated:
program 1 {(rewardsAmount24h.usd * 365 / programStake.usd * 100)} + program 2 {(rewardsAmount24h.usd * 365 / programStake.usd * 100)} +...

**Comment by ashachaf** [comment]
@pingustar please confirm this is handled in a different issue

**Comment by pingustar** [comment]
@ashachaf correct. You can find the implementation here: https://github.com/bancorprotocol/webapp-v3/blob/main/src/services/observables/pools.ts#L176
