### ISSUE TITLE
Staked in a non-whitelisted pool on Earn v2, position doesn't show up in the v2 portfolio

### ISSUE THREAD

**Issue by Yanivshechter1** [bancorprotocol/webapp-v3#294]
1. Stake in a non-WL v2 pool like CEEK. 
2. Check position on the v2 portfolio page. 
3. Rewards accrue but the position doesn't show up under "My Protected Positions"
![Screenshot 2022-05-09 at 09 43 06](https://user-images.githubusercontent.com/102954566/168028078-17e9292e-411b-40ff-9833-9731a55fc5ff.png)

**Comment by pingustar** [comment]
@Yanivshechter1 @ashachaf 

staking into non-whitelisted v2 pools will show under portfolio v1 tab
