### ISSUE TITLE
"View contract" and "Buy ETH with fiat" under a token in the holdings page of the portfolio v3 don't go anywhere

### ISSUE THREAD

**Issue by Yanivshechter1** [bancorprotocol/webapp-v3#295]
1. Go to portfolio
2. Press the "..." menu under a token in the holdings table
3. click "View Contract" or "Buy ETH with fiat."
![Screenshot 2022-05-09 at 09 59 33](https://user-images.githubusercontent.com/102954566/168028423-ecf881b4-267b-4da5-801a-eb34c1f3f19f.png)

**Comment by pingustar** [comment]
closing because we no longer use this UI @ashachaf
