### ISSUE TITLE
Check for Trading Enabled 

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp-v3#378]

**Comment by ashachaf** [comment]
decision flow:
When to show the token in the trade widget?
If the pool (available on v2) OR ((available in V3) AND (tradingEnable=true))

How to route and select best rate?
- If V3 pool exists -> 
-- If tradingEnable = true -> check v3 rate and select best rate
-- Else (tradingEnable = false), only route to v2
- Else (no v3 pool) -> route to v2
