### ISSUE TITLE
[BUG] Initiate withdrawal - handle balance and error

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp-v3#441]
**Describe the bug**
when i initiate a withdrawal with balance i no longer have, the process is stuck waiting for confirmation
<img width="955" alt="image" src="https://user-images.githubusercontent.com/40430285/172576336-bc08f151-1236-4144-971c-fca07bc0cf00.png">

**To Reproduce**
1. initiate withdrawal for the full balance
2. initiate another withdrawal for the full balance immediately after (while it is pending blockchain confirmation)
expected: 
1. receive error notification that the transaction have failed
2. reset the CTA to default
actual: 
1. there was no error
2. CTA is stuck on "waiting for confirmation"

**Comment by pingustar** [comment]
as discussed with @ashachaf we are moving this to general error handling and notifications
