### ISSUE TITLE
[BUG] The link to how to vote leads to a page not found.

### ISSUE THREAD

**Issue by Yanivshechter1** [bancorprotocol/webapp-v3#516]
**Describe the bug**
When a user clicks the "How to vote" link it leads him to a page not found.

**To Reproduce**
1. Go to the vote page 
2. Click the "How to vote" 

**Expected behavior**
“How to vote” should lead to https://support.bancor.network/hc/en-us/articles/5476957904914

**Screenshots**
<img width="1685" alt="Screen Shot 2022-06-23 at 11 17 12" src="https://user-images.githubusercontent.com/102954566/175251287-d132bbea-c36c-4ac3-bb46-961dbdc6acde.png">

**Comment by zavelevsky** [comment]
@Yanivshechter1 what page? Please provide URL of the destination page

**Comment by Yanivshechter1** [comment]
Added the link to the bug description
