### ISSUE TITLE
[BUG] Withdraw amount text field is not limited to any amount of digits.

### ISSUE THREAD

**Issue by Yanivshechter1** [bancorprotocol/webapp-v3#517]
**Describe the bug**
Withdraw amount text field is not limited to any amount of digits.

**To Reproduce**
1. Go to the portfolio page 
2. Withdraw on of the tokens you hold 
3. Insert a very very long number (more than 30 digits) 

**Expected behavior**
The text field should be limited to 18 digits after the dot and 12 digits before

**Screenshots**
<img width="1685" alt="Screen Shot 2022-06-23 at 11 25 40" src="https://user-images.githubusercontent.com/102954566/175252962-7260229b-66bf-4052-92fa-d360f2f4dddf.png">

**Comment by RanCohenn** [comment]
Stale
