### ISSUE TITLE
[BUG] Typo in withdraw window

### ISSUE THREAD

**Issue by Yanivshechter1** [bancorprotocol/webapp-v3#524]
**Describe the bug**
Typo in withdraw window

**To Reproduce**
1. Start 7 days cooldown 
2. Cancel the withdrawal prosses 
3. Look at the button at the bottom of the screen 

**Expected behavior**
Cancel and not "Canoel"

**Screenshots**
![106](https://user-images.githubusercontent.com/102954566/175803780-7a556bf5-d41c-480d-9dcf-ba12967ef8b2.png)

**Comment by zavelevsky** [comment]
The text has been fine since it was first written. It might be a rendering issue but without an environment to reproduce the issue I have no chance fixing it.
