### ISSUE TITLE
[BUG] Withdrawal message update 

### ISSUE THREAD

**Issue by Yanivshechter1** [bancorprotocol/webapp-v3#536]
Please change the text in the withdrawal screen to the text below. 

“BNT distribution supporting impermanent loss insurance and vault deficit accounting is currently paused.”

And clicking box has:

“I understand BNT distribution is paused and my withdrawal is exposed to IL and any vault deficit.”

**Comment by zavelevsky** [comment]
This text in in the orange box in withdrawal completion - and it has nothing to do with IL protection - it appears when the pool is unstable. In this case, withdrawal cannot be completed - so it's not only a warning.
Reassigning the issue to @Yanivshechter1

**Comment by Yanivshechter1** [comment]
Waiting for design feedback

**Comment by Yanivshechter1** [comment]
Part of issue #554
