### ISSUE TITLE
[BUG] Text and display changes in depositings' pop-up

### ISSUE THREAD

**Issue by Yanivshechter1** [bancorprotocol/webapp-v3#539]
**Describe the bug**
Text and display changes in depositings' pop-up

**To Reproduce**
1. Go to earn page 
2. Try to deposit any token 
*** There are more ways to get to the pop-up

**Expected behavior**

- [x]  text

Actual text - "Due to extreme market conditions, deposits are temporarily paused"
Expected  text - "Deposits are temporarily paused."

- [x]  display 
Actual - scrolling bars on the sides of the pop-up
Expected - No scrolling bars on the sides of the pop-up
**Screenshots**
![2022-06-27 17 01 47](https://user-images.githubusercontent.com/102954566/175959947-8d676926-5b93-4ca6-8e80-a30ee4bc0a1c.jpg)

**Comment by RanCohenn** [comment]
Fixed [here](https://github.com/bancorprotocol/webapp-v3/commit/412ea2fd4da12cf80c8bcd637b8f9fb5b0fa8dbe)
