### ISSUE TITLE
[BUG] Removing the Protected icon 

### ISSUE THREAD

**Issue by Yanivshechter1** [bancorprotocol/webapp-v3#542]
**Describe the bug**
As a result of the recent events, no pool is protected so the "Protected" icon should be removed 

**To Reproduce**
1. Go to earn page 

**Expected behavior**
1. Remove the icon from the V3 toggle 
2. Remove the icon from all pools in the V2 pools table 

**Screenshots**
<img width="450" alt="Screen Shot 2022-06-28 at 16 56 44" src="https://user-images.githubusercontent.com/102954566/176198065-e7d94d1d-2fae-416d-a179-a06067252c0b.png">
<img width="567" alt="Screen Shot 2022-06-28 at 17 02 01" src="https://user-images.githubusercontent.com/102954566/176198244-1c1ee407-3644-4d7c-956b-ac36fd8060a2.png">

**Comment by RanCohenn** [comment]
Fixed [here](https://github.com/bancorprotocol/webapp-v3/commit/fd424fc8dd236eedd4ff045104c8957bfb2082ed)
