### ISSUE TITLE
[BUG] The TKN amount overlaps the withdraw button when there are many digits 

### ISSUE THREAD

**Issue by Yanivshechter1** [bancorprotocol/webapp-v3#565]
**Describe the bug**
The TKN amount overlaps the withdraw button when there are many digits 

**To Reproduce**
1. Use wallet - 0x6d1005c19c5074003ca139af2a94a9aab565dacb
2. Go to portfolio 
3. Withdraw all SHIBGF tokens 
4. Look at the pending withdrawal

**Expected behavior**
The number is displayed without overlapping with the button

**Screenshots**
![image_2022-07-14_12-01-39](https://user-images.githubusercontent.com/102954566/178946422-19afabad-77d1-4e29-b53c-50212d11cbc1.png)

**Comment by zavelevsky** [comment]
@Yanivshechter1 how do you suggest we address this, design wise?

**Comment by Yanivshechter1** [comment]
Let's use abbreviation M for numbers with over 7 digits and when mouse hovering show the full number
