### ISSUE TITLE
External trade routing 

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp-v3#585]
as a user, i would like to have the option to trade tokens that are currently NOT supported on bancor (with any bancor pool). for this, we would like to integrate external routing solutions that are able to support additional tokens and any trade fee generated from this will be used by the Bancor DAO.

## Overview
This implementation will only be included in the trade widget and will allow users to see, search and select tokens that do not have Bancor pools. 

## Flow
1. visit the /trade page
2. allow users to select from/to token from a list that includes tokens that are supported by bancor (current list) AND tokens that are supported by the external router
3. IF source OR target tokens are NOT supported by Bancor -> trigger the transaction to the external router

## external token USD rates
since we would like to support the USD rate we display and since these tokens do not have pools on bancor, we wont have this rate available, we would need to create a new flow to get this value.
1. assume all tokens supported by the external routing, will also have a pair with ETH
2. use the external routing to get ETH rate for these tokens 
3. use our internal ETH-USD rate to calculate the token's USD value

## External router
0x documentation is fairly straight forward to follow and we will use them for initial integration.

### step 1 - supported tokens
since 0x api is connected to many trading options, it is safe to assume they support the largest list of available tokens. for this, we can use the coinGecko tokenList to show additional tokens which are not supported by Bancor pools directly.
https://docs.0x.org/developer-resources/api-faqs#how-do-i-query-what-tokens-are-available-to-be-swapped-through-the-api

### step 2 - get rate
[0x price api](https://docs.0x.org/0x-api-swap/api-references/get-swap-v1-price)
after tokens selection, we would like to query this api endpoint to get the price quote based on the input amounts.

**empty state**
in order to get the "spot rate" of the tokens, we need to do the following:
```
set $checkAmount == 1
call api with $checkAmount
If error, set $checkAmount = $checkAmount*10 and call api again
```

**input state**
once a user input values, use these values in the api call

**slippage indication**
calculate as we do today but use these values
- empty state response 
- input state response 

### step 3 - send transaction
once a user indicates the desire to trade (by clicking the CTA), 
[0x quote api](https://docs.0x.org/0x-api-swap/api-references/get-swap-v1-quote)

**Affiliate Fee**
when sending a transaction using the frontend, we would like to append the following values:
- feeRecipient -> 0x5f7a009664B771E889751f4FD721aDc439033ECD
- buyTokenPercentageFee -> 0.5

calling the /quote api will result in an unsigned transaction.
this data is needed to create a metamask transaction (check allowance as always)

### External trade indication 
* Trade widget - When user trade an unsupported token change the v2/v3 indication
- change "Best rate" -> "Rate"
- if external route -> "External" with a tooltip when hovering 
https://www.figma.com/file/fwADI9wqDrRAdlMX8EddCw/Bancor-v3?node-id=16419%3A237509

#### references and examples
https://docs.alchemy.com/alchemy/road-to-web3/weekly-learning-challenges/9.-how-to-build-a-token-swap-dapp-with-0x-api#part-9.-perform-the-swap
https://docs.0x.org/0x-api-swap/api-references/get-swap-v1-price
https://docs.0x.org/0x-api-swap/api-references/get-swap-v1-quote

**Comment by Yanivshechter1** [comment]
@pingustar Added design for trade widget indicator

**Comment by Yanivshechter1** [comment]
@pingustar Added a small change for the trade widget indicator
