### ISSUE TITLE
[BUG] Missing token icons at the pools table 

### ISSUE THREAD

**Issue by Yanivshechter1** [bancorprotocol/webapp-v3#586]
**Describe the bug**
There are missing token icons at the pools table 
**To Reproduce**
1. Go to the pools page
2. Look at the tables in V3+2

**Expected behavior**
All tokens have icons 

Attach a file with part of the missing icons
[Icons SVG.zip](https://github.com/bancorprotocol/webapp-v3/files/9206344/Icons.SVG.zip)

**Comment by RanCohenn** [comment]
added
