### ISSUE TITLE
[BUG] redirects updates

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp-v3#591]
we have several pages that are links from different sources and lead to a dead page.
we should create a redirect to fix them and bring them to a page we manage.

- [x] bancor.network/discover -> home.bancor.network
- [ ] https://www.bancor.network/token/WBTC -> https://app.bancor.network/earn
should be set as wildcard where
https://www.bancor.network/token/* -> https://app.bancor.network/earn

**Comment by zavelevsky** [comment]
We will address it using bulk redirects in cloudflare - and avoid using regular page rules and wildcards. 
use this:
https://developers.cloudflare.com/rules/bulk-redirects/how-it-works/#matching-the-source-url-of-redirects
