### ISSUE TITLE
Deposit update 

### ISSUE THREAD

**Issue by Yanivshechter1** [bancorprotocol/webapp-v3#610]
As a user, I would like to know if a pool I'm about deposit to is in deficit or surplus and how it may affect my holdings. 

## High level 
Adding an indication for users about the pool status and explaining what it means and how it affects them. 

## Mockups ##
Web - https://www.figma.com/file/fwADI9wqDrRAdlMX8EddCw/Bancor-v3?node-id=15566%3A234470
Mobile - https://www.figma.com/file/fwADI9wqDrRAdlMX8EddCw/Bancor-v3?node-id=16094%3A227793

## changes
we are adding 4 new elements to the deposit screen.
they have different behavior based on the pool deficit condition (which will be explained below)
the sections are:
1. vault balance 
* https://www.figma.com/file/fwADI9wqDrRAdlMX8EddCw/Bancor-v3?node-id=15566%3A234470 (notice different font color based on positive/negative pool value)
* Use the same calculation we currently have on the withdrawal flow
```
expected calculation:
{current pool balance} / {total staked balance}
example:
(80 / 100) - 1 = -0.2 -> to % multiple by 100 -> -20% 
(110 / 100) - 1 = +0.1 -> to % multiple by 100 -> +10%
```
* (I) icon and a tooltip explaining the meaning of vault balance.
Text -  "The % of tokens available" 
2. disclaimer text
* Surplus - "This pool is currently NOT in deficit. This may change over time. Should this pool be in deficit when you’re ready to withdraw, your deposit will accrue the pool deficit at that time."
* Deficit -  
**Empty state** - "This pool is in deficit. If an immediate withdrawal were initiated, the claimable amount will be --TKK/ETH. Its value and deficit amount can change over time." 
**Input**  - "This pool is in deficit. If an immediate withdrawal were initiated, the claimable amount will be xxxxxxxx TKK/ETH. Its value and deficit amount can change over time." 
*** For calculation, use the same function we are using when showing the user he withdraws the amount in deficit 
3. checkbox
* https://www.figma.com/file/fwADI9wqDrRAdlMX8EddCw/Bancor-v3?node-id=15824%3A244285
* Add warning text and checkbox of BNT distribution is disabled as we have now in withdraw flow 
* CTA button is enabled only if the user checks the BNT warning
4. faq
* https://www.figma.com/file/fwADI9wqDrRAdlMX8EddCw/Bancor-v3?node-id=15824%3A244253
* By default, FAQ are close 
* There are two FAQs
* Use the text from Figma 
* "Learn more" - link TBD 
5. Auto-filling of the deposit amount 
* Removing the 25/50/75/100% deposit from the available balance.
* Add "MAX" button next to the available amount 
** Clicking the button will auto-fill the deposit amount with the max available balance
### 1. Deposit while the vault is in surplus 
* Pool has more tokens than its commitment 
https://www.figma.com/file/fwADI9wqDrRAdlMX8EddCw/Bancor-v3?node-id=15824%3A244266
1. Vault balance - Use the calculation above and mark it in blue 
2. Disclaimer text - Use the surplus option 
3. Add the checkbox 
4. Add FAQ section 

### 2. Deposit while the vault is in deficit 
* Pool has fewer tokens than its commitment 
https://www.figma.com/file/fwADI9wqDrRAdlMX8EddCw/Bancor-v3?node-id=15824%3A244267
1. Vault balance - Use the calculation above and mark it in red 
2. Disclaimer text - Use the deficit  option 
3. Add the checkbox 
4. Add FAQ section 
### 3. Deposit BNT
* BNT pool cannot be in deficit or surplus 
Do not add the option above, everything stays the same as of now.

**Comment by zavelevsky** [comment]
Blocked by: #617
