### ISSUE TITLE
[BUG] top banner reopens after refresh

### ISSUE THREAD

**Issue by zavelevsky** [bancorprotocol/webapp-v3#667]
**Describe the bug**
The top banner saying "BNT distribution was paused to prevent loss of users funds." reopens after refresh even it the user closed it

**To Reproduce**

1. Go to the app
2. See the "BNT distribution was paused to prevent loss of users funds." showing
3. Click x to close the banner
4. refresh the app
5. The banner reappears! 

**Expected behavior**
The banner no longer appears

**Comment by ashachaf** [comment]
fixed. using external service.
