### ISSUE TITLE
update analytics URL

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp-v3#743]
go to app.bancor.network
click to open the menu (top right)
menu item: "Analytics"
current redirect URL: https://dune.com/Bancor/bancor_1
updated redirect URL: https://dune.com/bancordata/bancor-table-of-contents

**Comment by zavelevsky** [comment]
@ashachaf we should just remove this because the other item goes to that URL

**Comment by zavelevsky** [comment]
fixed
